### ISSUE TITLE
Original authors

### ISSUE THREAD

**Issue by zeppelin** [movableink/buffered-proxy#3]
BufferedProxy was originally developed by Kris Selden, used in the Yapp codebase, published by Luke Melia: https://gist.github.com/lukemelia/5632776

There's also a [video recorded](https://www.youtube.com/watch?v=ysduY0ocUoA#t=1978) at the meetup explaining the concept in depth.

(Just reflecting to the credits in README)

**Comment by mnutt** [comment]
Thanks, sorry I missed that.  I will get it updated.
